// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: Binding.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Binding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queue         *Queue                 `protobuf:"bytes,1,opt,name=queue,proto3" json:"queue,omitempty"`
	Exchange      *Exchange              `protobuf:"bytes,2,opt,name=exchange,proto3" json:"exchange,omitempty"`
	RoutingKey    string                 `protobuf:"bytes,3,opt,name=routing_key,json=routingKey,proto3" json:"routing_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Binding) Reset() {
	*x = Binding{}
	mi := &file_Binding_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Binding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Binding) ProtoMessage() {}

func (x *Binding) ProtoReflect() protoreflect.Message {
	mi := &file_Binding_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Binding.ProtoReflect.Descriptor instead.
func (*Binding) Descriptor() ([]byte, []int) {
	return file_Binding_proto_rawDescGZIP(), []int{0}
}

func (x *Binding) GetQueue() *Queue {
	if x != nil {
		return x.Queue
	}
	return nil
}

func (x *Binding) GetExchange() *Exchange {
	if x != nil {
		return x.Exchange
	}
	return nil
}

func (x *Binding) GetRoutingKey() string {
	if x != nil {
		return x.RoutingKey
	}
	return ""
}

var File_Binding_proto protoreflect.FileDescriptor

const file_Binding_proto_rawDesc = "" +
	"\n" +
	"\rBinding.proto\x12\bcontract\x1a\vError.proto\x1a\x0eExchange.proto\x1a\vQueue.proto\"\x81\x01\n" +
	"\aBinding\x12%\n" +
	"\x05queue\x18\x01 \x01(\v2\x0f.contract.QueueR\x05queue\x12.\n" +
	"\bexchange\x18\x02 \x01(\v2\x12.contract.ExchangeR\bexchange\x12\x1f\n" +
	"\vrouting_key\x18\x03 \x01(\tR\n" +
	"routingKey2j\n" +
	"\x0eBindingService\x12*\n" +
	"\x04Bind\x12\x11.contract.Binding\x1a\x0f.contract.Error\x12,\n" +
	"\x06Unbind\x12\x11.contract.Binding\x1a\x0f.contract.ErrorB\vZ\t./grpc/pbb\x06proto3"

var (
	file_Binding_proto_rawDescOnce sync.Once
	file_Binding_proto_rawDescData []byte
)

func file_Binding_proto_rawDescGZIP() []byte {
	file_Binding_proto_rawDescOnce.Do(func() {
		file_Binding_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Binding_proto_rawDesc), len(file_Binding_proto_rawDesc)))
	})
	return file_Binding_proto_rawDescData
}

var file_Binding_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_Binding_proto_goTypes = []any{
	(*Binding)(nil),  // 0: contract.Binding
	(*Queue)(nil),    // 1: contract.Queue
	(*Exchange)(nil), // 2: contract.Exchange
	(*Error)(nil),    // 3: contract.Error
}
var file_Binding_proto_depIdxs = []int32{
	1, // 0: contract.Binding.queue:type_name -> contract.Queue
	2, // 1: contract.Binding.exchange:type_name -> contract.Exchange
	0, // 2: contract.BindingService.Bind:input_type -> contract.Binding
	0, // 3: contract.BindingService.Unbind:input_type -> contract.Binding
	3, // 4: contract.BindingService.Bind:output_type -> contract.Error
	3, // 5: contract.BindingService.Unbind:output_type -> contract.Error
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_Binding_proto_init() }
func file_Binding_proto_init() {
	if File_Binding_proto != nil {
		return
	}
	file_Error_proto_init()
	file_Exchange_proto_init()
	file_Queue_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Binding_proto_rawDesc), len(file_Binding_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_Binding_proto_goTypes,
		DependencyIndexes: file_Binding_proto_depIdxs,
		MessageInfos:      file_Binding_proto_msgTypes,
	}.Build()
	File_Binding_proto = out.File
	file_Binding_proto_goTypes = nil
	file_Binding_proto_depIdxs = nil
}
