// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.1
// source: Binding.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BindingService_Bind_FullMethodName   = "/contract.BindingService/Bind"
	BindingService_Unbind_FullMethodName = "/contract.BindingService/Unbind"
)

// BindingServiceClient is the client API for BindingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BindingServiceClient interface {
	Bind(ctx context.Context, in *Binding, opts ...grpc.CallOption) (*Error, error)
	Unbind(ctx context.Context, in *Binding, opts ...grpc.CallOption) (*Error, error)
}

type bindingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBindingServiceClient(cc grpc.ClientConnInterface) BindingServiceClient {
	return &bindingServiceClient{cc}
}

func (c *bindingServiceClient) Bind(ctx context.Context, in *Binding, opts ...grpc.CallOption) (*Error, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Error)
	err := c.cc.Invoke(ctx, BindingService_Bind_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bindingServiceClient) Unbind(ctx context.Context, in *Binding, opts ...grpc.CallOption) (*Error, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Error)
	err := c.cc.Invoke(ctx, BindingService_Unbind_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BindingServiceServer is the server API for BindingService service.
// All implementations must embed UnimplementedBindingServiceServer
// for forward compatibility.
type BindingServiceServer interface {
	Bind(context.Context, *Binding) (*Error, error)
	Unbind(context.Context, *Binding) (*Error, error)
	mustEmbedUnimplementedBindingServiceServer()
}

// UnimplementedBindingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBindingServiceServer struct{}

func (UnimplementedBindingServiceServer) Bind(context.Context, *Binding) (*Error, error) {
	return nil, status.Error(codes.Unimplemented, "method Bind not implemented")
}
func (UnimplementedBindingServiceServer) Unbind(context.Context, *Binding) (*Error, error) {
	return nil, status.Error(codes.Unimplemented, "method Unbind not implemented")
}
func (UnimplementedBindingServiceServer) mustEmbedUnimplementedBindingServiceServer() {}
func (UnimplementedBindingServiceServer) testEmbeddedByValue()                        {}

// UnsafeBindingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BindingServiceServer will
// result in compilation errors.
type UnsafeBindingServiceServer interface {
	mustEmbedUnimplementedBindingServiceServer()
}

func RegisterBindingServiceServer(s grpc.ServiceRegistrar, srv BindingServiceServer) {
	// If the following call panics, it indicates UnimplementedBindingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BindingService_ServiceDesc, srv)
}

func _BindingService_Bind_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Binding)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BindingServiceServer).Bind(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BindingService_Bind_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BindingServiceServer).Bind(ctx, req.(*Binding))
	}
	return interceptor(ctx, in, info, handler)
}

func _BindingService_Unbind_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Binding)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BindingServiceServer).Unbind(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BindingService_Unbind_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BindingServiceServer).Unbind(ctx, req.(*Binding))
	}
	return interceptor(ctx, in, info, handler)
}

// BindingService_ServiceDesc is the grpc.ServiceDesc for BindingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BindingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "contract.BindingService",
	HandlerType: (*BindingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Bind",
			Handler:    _BindingService_Bind_Handler,
		},
		{
			MethodName: "Unbind",
			Handler:    _BindingService_Unbind_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Binding.proto",
}
