// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: Exchange.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Exchange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Durable       *bool                  `protobuf:"varint,3,opt,name=durable,proto3,oneof" json:"durable,omitempty"`
	AutoDeleted   *bool                  `protobuf:"varint,4,opt,name=auto_deleted,json=autoDeleted,proto3,oneof" json:"auto_deleted,omitempty"`
	Internal      *bool                  `protobuf:"varint,5,opt,name=internal,proto3,oneof" json:"internal,omitempty"`
	NoWait        *bool                  `protobuf:"varint,6,opt,name=no_wait,json=noWait,proto3,oneof" json:"no_wait,omitempty"`
	Args          map[string]*anypb.Any  `protobuf:"bytes,7,rep,name=args,proto3" json:"args,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Exchange) Reset() {
	*x = Exchange{}
	mi := &file_Exchange_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Exchange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Exchange) ProtoMessage() {}

func (x *Exchange) ProtoReflect() protoreflect.Message {
	mi := &file_Exchange_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Exchange.ProtoReflect.Descriptor instead.
func (*Exchange) Descriptor() ([]byte, []int) {
	return file_Exchange_proto_rawDescGZIP(), []int{0}
}

func (x *Exchange) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Exchange) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Exchange) GetDurable() bool {
	if x != nil && x.Durable != nil {
		return *x.Durable
	}
	return false
}

func (x *Exchange) GetAutoDeleted() bool {
	if x != nil && x.AutoDeleted != nil {
		return *x.AutoDeleted
	}
	return false
}

func (x *Exchange) GetInternal() bool {
	if x != nil && x.Internal != nil {
		return *x.Internal
	}
	return false
}

func (x *Exchange) GetNoWait() bool {
	if x != nil && x.NoWait != nil {
		return *x.NoWait
	}
	return false
}

func (x *Exchange) GetArgs() map[string]*anypb.Any {
	if x != nil {
		return x.Args
	}
	return nil
}

var File_Exchange_proto protoreflect.FileDescriptor

const file_Exchange_proto_rawDesc = "" +
	"\n" +
	"\x0eExchange.proto\x12\bcontract\x1a\x19google/protobuf/any.proto\x1a\vError.proto\"\xef\x02\n" +
	"\bExchange\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1d\n" +
	"\adurable\x18\x03 \x01(\bH\x00R\adurable\x88\x01\x01\x12&\n" +
	"\fauto_deleted\x18\x04 \x01(\bH\x01R\vautoDeleted\x88\x01\x01\x12\x1f\n" +
	"\binternal\x18\x05 \x01(\bH\x02R\binternal\x88\x01\x01\x12\x1c\n" +
	"\ano_wait\x18\x06 \x01(\bH\x03R\x06noWait\x88\x01\x01\x120\n" +
	"\x04args\x18\a \x03(\v2\x1c.contract.Exchange.ArgsEntryR\x04args\x1aM\n" +
	"\tArgsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\x05value:\x028\x01B\n" +
	"\n" +
	"\b_durableB\x0f\n" +
	"\r_auto_deletedB\v\n" +
	"\t_internalB\n" +
	"\n" +
	"\b_no_wait2H\n" +
	"\x0fExchangeService\x125\n" +
	"\x0eCreateExchange\x12\x12.contract.Exchange\x1a\x0f.contract.ErrorB\vZ\t./grpc/pbb\x06proto3"

var (
	file_Exchange_proto_rawDescOnce sync.Once
	file_Exchange_proto_rawDescData []byte
)

func file_Exchange_proto_rawDescGZIP() []byte {
	file_Exchange_proto_rawDescOnce.Do(func() {
		file_Exchange_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Exchange_proto_rawDesc), len(file_Exchange_proto_rawDesc)))
	})
	return file_Exchange_proto_rawDescData
}

var file_Exchange_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_Exchange_proto_goTypes = []any{
	(*Exchange)(nil),  // 0: contract.Exchange
	nil,               // 1: contract.Exchange.ArgsEntry
	(*anypb.Any)(nil), // 2: google.protobuf.Any
	(*Error)(nil),     // 3: contract.Error
}
var file_Exchange_proto_depIdxs = []int32{
	1, // 0: contract.Exchange.args:type_name -> contract.Exchange.ArgsEntry
	2, // 1: contract.Exchange.ArgsEntry.value:type_name -> google.protobuf.Any
	0, // 2: contract.ExchangeService.CreateExchange:input_type -> contract.Exchange
	3, // 3: contract.ExchangeService.CreateExchange:output_type -> contract.Error
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_Exchange_proto_init() }
func file_Exchange_proto_init() {
	if File_Exchange_proto != nil {
		return
	}
	file_Error_proto_init()
	file_Exchange_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Exchange_proto_rawDesc), len(file_Exchange_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_Exchange_proto_goTypes,
		DependencyIndexes: file_Exchange_proto_depIdxs,
		MessageInfos:      file_Exchange_proto_msgTypes,
	}.Build()
	File_Exchange_proto = out.File
	file_Exchange_proto_goTypes = nil
	file_Exchange_proto_depIdxs = nil
}
