// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: Queue.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Queue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Durable       *bool                  `protobuf:"varint,2,opt,name=durable,proto3,oneof" json:"durable,omitempty"`
	DeleteUnused  *bool                  `protobuf:"varint,3,opt,name=delete_unused,json=deleteUnused,proto3,oneof" json:"delete_unused,omitempty"`
	Exclusive     *bool                  `protobuf:"varint,4,opt,name=exclusive,proto3,oneof" json:"exclusive,omitempty"`
	NoWait        *bool                  `protobuf:"varint,5,opt,name=no_wait,json=noWait,proto3,oneof" json:"no_wait,omitempty"`
	Args          map[string]*anypb.Any  `protobuf:"bytes,6,rep,name=args,proto3" json:"args,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Queue) Reset() {
	*x = Queue{}
	mi := &file_Queue_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Queue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Queue) ProtoMessage() {}

func (x *Queue) ProtoReflect() protoreflect.Message {
	mi := &file_Queue_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Queue.ProtoReflect.Descriptor instead.
func (*Queue) Descriptor() ([]byte, []int) {
	return file_Queue_proto_rawDescGZIP(), []int{0}
}

func (x *Queue) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Queue) GetDurable() bool {
	if x != nil && x.Durable != nil {
		return *x.Durable
	}
	return false
}

func (x *Queue) GetDeleteUnused() bool {
	if x != nil && x.DeleteUnused != nil {
		return *x.DeleteUnused
	}
	return false
}

func (x *Queue) GetExclusive() bool {
	if x != nil && x.Exclusive != nil {
		return *x.Exclusive
	}
	return false
}

func (x *Queue) GetNoWait() bool {
	if x != nil && x.NoWait != nil {
		return *x.NoWait
	}
	return false
}

func (x *Queue) GetArgs() map[string]*anypb.Any {
	if x != nil {
		return x.Args
	}
	return nil
}

var File_Queue_proto protoreflect.FileDescriptor

const file_Queue_proto_rawDesc = "" +
	"\n" +
	"\vQueue.proto\x12\bcontract\x1a\x19google/protobuf/any.proto\x1a\vError.proto\"\xdb\x02\n" +
	"\x05Queue\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\adurable\x18\x02 \x01(\bH\x00R\adurable\x88\x01\x01\x12(\n" +
	"\rdelete_unused\x18\x03 \x01(\bH\x01R\fdeleteUnused\x88\x01\x01\x12!\n" +
	"\texclusive\x18\x04 \x01(\bH\x02R\texclusive\x88\x01\x01\x12\x1c\n" +
	"\ano_wait\x18\x05 \x01(\bH\x03R\x06noWait\x88\x01\x01\x12-\n" +
	"\x04args\x18\x06 \x03(\v2\x19.contract.Queue.ArgsEntryR\x04args\x1aM\n" +
	"\tArgsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\x05value:\x028\x01B\n" +
	"\n" +
	"\b_durableB\x10\n" +
	"\x0e_delete_unusedB\f\n" +
	"\n" +
	"_exclusiveB\n" +
	"\n" +
	"\b_no_wait2p\n" +
	"\fQueueService\x12/\n" +
	"\vCreateQueue\x12\x0f.contract.Queue\x1a\x0f.contract.Error\x12/\n" +
	"\vDeleteQueue\x12\x0f.contract.Queue\x1a\x0f.contract.ErrorB\vZ\t./grpc/pbb\x06proto3"

var (
	file_Queue_proto_rawDescOnce sync.Once
	file_Queue_proto_rawDescData []byte
)

func file_Queue_proto_rawDescGZIP() []byte {
	file_Queue_proto_rawDescOnce.Do(func() {
		file_Queue_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Queue_proto_rawDesc), len(file_Queue_proto_rawDesc)))
	})
	return file_Queue_proto_rawDescData
}

var file_Queue_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_Queue_proto_goTypes = []any{
	(*Queue)(nil),     // 0: contract.Queue
	nil,               // 1: contract.Queue.ArgsEntry
	(*anypb.Any)(nil), // 2: google.protobuf.Any
	(*Error)(nil),     // 3: contract.Error
}
var file_Queue_proto_depIdxs = []int32{
	1, // 0: contract.Queue.args:type_name -> contract.Queue.ArgsEntry
	2, // 1: contract.Queue.ArgsEntry.value:type_name -> google.protobuf.Any
	0, // 2: contract.QueueService.CreateQueue:input_type -> contract.Queue
	0, // 3: contract.QueueService.DeleteQueue:input_type -> contract.Queue
	3, // 4: contract.QueueService.CreateQueue:output_type -> contract.Error
	3, // 5: contract.QueueService.DeleteQueue:output_type -> contract.Error
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_Queue_proto_init() }
func file_Queue_proto_init() {
	if File_Queue_proto != nil {
		return
	}
	file_Error_proto_init()
	file_Queue_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Queue_proto_rawDesc), len(file_Queue_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_Queue_proto_goTypes,
		DependencyIndexes: file_Queue_proto_depIdxs,
		MessageInfos:      file_Queue_proto_msgTypes,
	}.Build()
	File_Queue_proto = out.File
	file_Queue_proto_goTypes = nil
	file_Queue_proto_depIdxs = nil
}
